<script lang="ts">
  import { loadCharacterCatalog, type CharacterCatalogEntry } from '@/lib/catalog/character-catalog';
  import { watchFactorCatalog } from '@/lib/catalog/factor-catalog';
  let characters = $state.raw(new Map<number, CharacterCatalogEntry>());
  $effect(() => { void loadCharacterCatalog().then(data => characters = data).catch(reason => actionError = reason.message); return watchFactorCatalog(); });
  import AppPage from '@/layouts/AppPage.svelte';
  import Banner from '@/components/Banner.svelte';
  import Button from '@/components/Button.svelte';
  import Card from '@/components/Card.svelte';
  import DataTable from '@/components/DataTable.svelte';
  import Dialog from '@/components/Dialog.svelte';
  import EmptyState from '@/components/EmptyState.svelte';
  import FileDrop from '@/components/FileDrop.svelte';
  import FilterChip from '@/components/FilterChip.svelte';
  import IconButton from '@/components/IconButton.svelte';
  import ResultToolbar from '@/components/ResultToolbar.svelte';
  import RaceSchedule from '@/components/RaceSchedule.svelte';
  import SelectField from '@/components/SelectField.svelte';
  import Spinner from '@/components/Spinner.svelte';
  import Tabs from '@/components/Tabs.svelte';
  import TextField from '@/components/TextField.svelte';
  import VeteranListItem from '@/components/VeteranListItem.svelte';
  import VeteranSelector from '@/components/VeteranSelector.svelte';
  import VeteranSummary from '@/components/VeteranSummary.svelte';
  import WorkspaceSwitcher from '@/components/WorkspaceSwitcher.svelte';
  import { activeWorkspace } from '@/lib/workspaces/workspace-state';
  import { importVeterans, loadVeterans, removeVeteran, upsertVeteran, veteranRecords, veteranRecordsError, veteranRecordsLoading } from '@/lib/veterans/veteran-state';
  import { veteranRepository } from '@/lib/veterans/veteran-repository';
  import { veteranAffinityRepository } from '@/lib/veterans/affinity-repository';
  import { rankVeteranPairs, VeteranAffinityEngine, type AffinityData, type VeteranPairScore } from '@/lib/veterans/affinity-engine';
  import { loadCatalog } from '@/pages/database/catalog-repository';
  import { factorCategory, type FactorCategory } from '@/lib/catalog/factor-catalog';
  import { veteranToUi } from './veteran-adapter';
  import { loadRaceSchedule } from '@/lib/catalog/race-catalog';
  import SparkProcDialog from './SparkProcDialog.svelte';
  import type { RaceScheduleYear } from '@/components/race-types';

  let section = $state('library'); let search = $state(''); let selectedId = $state(''); let sort = $state('updated'); let view = $state<'list' | 'grid'>('list');
  let factorFilters = $state<FactorCategory[]>([]);
  let firstParent = $state(''); let secondParent = $state(''); let targetCharacterId = $state(''); let importMessage = $state(''); let actionError = $state(''); let deleting = $state(''); let addOpen = $state(false); let saving = $state(false);
  let affinityData = $state.raw<AffinityData>(); let affinityLoading = $state(false); let affinityError = $state(''); let targetOptions = $state.raw<{ value: string; label: string }[]>([]); let pairRankings = $state.raw<VeteranPairScore[]>([]); let ranking = $state(false); let affinityRequest: Promise<void> | undefined;
  let newName = $state(''); let newCardId = $state(''); let newRankScore = $state(''); let newSpeed = $state(''); let newStamina = $state(''); let newPower = $state(''); let newGuts = $state(''); let newWisdom = $state('');
  let sparkOpen = $state(false); let scheduleLoading = $state(false); let raceSearch = $state(''); let scheduleYears = $state.raw<RaceScheduleYear[]>([]); let selectedRaceIds = $state<string[]>([]); let scheduleToken = 0;
  const uiRecords = $derived($veteranRecords.map((record) => veteranToUi(record, $activeWorkspace.label, characters)));
  const sections = $derived([{ id: 'library', label: 'Library', badge: String(uiRecords.length) }, { id: 'optimizer', label: 'Optimizer' }, { id: 'affinity', label: 'Affinity' }, { id: 'planner', label: 'Race planner' }]);
  const filtered = $derived.by(() => { const query = search.trim().toLowerCase(); const values = uiRecords.filter((veteran) => { const source = $veteranRecords.find((record) => record.recordId === veteran.id); const text = `${veteran.name} ${veteran.detail ?? ''} ${veteran.scenario ?? ''} ${veteran.sparks.flatMap((group) => group.items.map((item) => item.name)).join(' ')}`.toLowerCase(); return (!query || text.includes(query)) && factorFilters.every((category) => source?.factors.some((factor) => factorCategory(factor.id) === category)); }); return [...values].sort((left, right) => sort === 'score' ? (right.score ?? 0) - (left.score ?? 0) : sort === 'affinity' ? right.affinity - left.affinity : (right.updated ?? '').localeCompare(left.updated ?? '')); });
  const selected = $derived(uiRecords.find((veteran) => veteran.id === selectedId) ?? filtered[0]);
  const selectorOptions = $derived(uiRecords.map((veteran) => ({ id: veteran.id, name: veteran.name, detail: veteran.detail ?? '', image: veteran.image, rank: veteran.rank, workspace: veteran.workspace, updated: veteran.updated })));
  const parentOne = $derived($veteranRecords.find((record) => record.recordId === firstParent)); const parentTwo = $derived($veteranRecords.find((record) => record.recordId === secondParent));
  const sharedFactors = $derived(parentOne && parentTwo ? [...new Set(parentOne.factors.map((item) => item.id))].filter((id) => parentTwo.factors.some((item) => item.id === id)).length : 0);
  const affinityEngine = $derived(affinityData ? new VeteranAffinityEngine(affinityData) : undefined);
  const relation = $derived(affinityEngine && parentOne && parentTwo && Number(targetCharacterId) ? affinityEngine.scoreVeteranPair(Number(targetCharacterId), parentOne, parentTwo) : undefined);
  const plannedYears = $derived(scheduleYears.map((year) => ({ ...year, slots: year.slots.map((slot) => ({ ...slot, races: slot.races.map((race) => ({ ...race, selected: selectedRaceIds.includes(race.id) })) })) })));
  const rankingRows = $derived(pairRankings.map((entry, index) => ({ rank: index + 1, parentOne: veteranLabel(entry.parentOne.recordId), parentTwo: veteranLabel(entry.parentTwo.recordId), p1: entry.relation.parentOneTotal, p2: entry.relation.parentTwoTotal, pair: entry.relation.parentPair, total: entry.relation.total })));
  const rankingColumns = [{ key: 'rank', label: '#', numeric: true }, { key: 'parentOne', label: 'Parent 1', priority: 'primary' as const }, { key: 'parentTwo', label: 'Parent 2', priority: 'primary' as const }, { key: 'p1', label: 'P1 branch', numeric: true, priority: 'secondary' as const }, { key: 'p2', label: 'P2 branch', numeric: true, priority: 'secondary' as const }, { key: 'pair', label: 'Pair', numeric: true }, { key: 'total', label: 'Relation', numeric: true }];

  function resetMessages(): void { importMessage = ''; actionError = ''; }
  function toggleFactor(category: FactorCategory): void { factorFilters = factorFilters.includes(category) ? factorFilters.filter((value) => value !== category) : [...factorFilters, category]; }
  async function files(files: FileList): Promise<void> { resetMessages(); try { const payloads = await Promise.all([...files].map(async (file) => JSON.parse(await file.text()) as unknown)); let inserted = 0; let updated = 0; for (const payload of payloads) { const result = await importVeterans($activeWorkspace.id, payload); inserted += result.inserted; updated += result.updated; } importMessage = `Imported ${inserted} new and updated ${updated} existing Veterans.`; } catch (error) { actionError = error instanceof Error ? error.message : 'Import failed.'; } }
  async function remove(id: string): Promise<void> { const veteran = uiRecords.find((item) => item.id === id); if (!window.confirm(`Delete ${veteran?.name ?? 'this Veteran'} from ${$activeWorkspace.label}?`)) return; deleting = id; try { await removeVeteran($activeWorkspace.id, id); if (selectedId === id) selectedId = ''; } catch (error) { actionError = error instanceof Error ? error.message : 'Delete failed.'; } finally { deleting = ''; } }
  async function exportOne(id: string): Promise<void> { const record = $veteranRecords.find((item) => item.recordId === id); if (record) download(`${record.name || record.recordId}.json`, record); }
  async function exportAll(): Promise<void> { download(`uma-moe-veterans-${$activeWorkspace.id.replace(':','-')}.json`, await veteranRepository.export($activeWorkspace.id)); }
  function download(name: string, value: unknown): void { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name.replace(/[^a-z0-9._-]/gi, '-'); anchor.click(); URL.revokeObjectURL(url); }
  async function addVeteran(): Promise<void> { resetMessages(); saving = true; try { await upsertVeteran($activeWorkspace.id, { card_id: Number(newCardId), name: newName.trim() || null, rank_score: Number(newRankScore) || null, speed: Number(newSpeed) || 0, stamina: Number(newStamina) || 0, power: Number(newPower) || 0, guts: Number(newGuts) || 0, wisdom: Number(newWisdom) || 0, source: 'unknown', factors: [], skills: [], parents: [] }); addOpen = false; newName = newCardId = newRankScore = newSpeed = newStamina = newPower = newGuts = newWisdom = ''; importMessage = 'Veteran added to the active workspace.'; } catch (error) { actionError = error instanceof Error ? error.message : 'Veteran could not be saved.'; } finally { saving = false; } }
  function veteranLabel(recordId: string): string { return uiRecords.find((record) => record.id === recordId)?.name ?? recordId; }
  function toggleRace(id: string): void { selectedRaceIds = selectedRaceIds.includes(id) ? selectedRaceIds.filter((value) => value !== id) : [...selectedRaceIds, id]; }
  async function ensureAffinity(): Promise<void> {
    if (affinityData || affinityRequest) return affinityRequest;
    affinityLoading = true; affinityError = '';
    affinityRequest = Promise.all([veteranAffinityRepository.load(), loadCatalog('characters')]).then(([data, characters]) => {
      affinityData = data;
      const seen = new Set<number>();
      targetOptions = characters.flatMap((character) => { const id = Math.floor(Number(character.id) / 100); if (!id || seen.has(id)) return []; seen.add(id); return [{ value: String(id), label: character.title }]; });
      if (!targetCharacterId) targetCharacterId = targetOptions[0]?.value ?? '';
    }).catch((error) => { affinityError = error instanceof Error ? error.message : 'Affinity data could not be loaded.'; }).finally(() => { affinityLoading = false; affinityRequest = undefined; });
    return affinityRequest;
  }
  async function rankPairs(): Promise<void> {
    if (!affinityEngine || !Number(targetCharacterId)) return;
    ranking = true;
    await new Promise<void>((resolve) => requestAnimationFrame(() => resolve()));
    pairRankings = rankVeteranPairs(affinityEngine, Number(targetCharacterId), $veteranRecords, 30);
    ranking = false;
  }
  $effect(() => { const workspace = $activeWorkspace.id; selectedId = ''; firstParent = ''; secondParent = ''; void loadVeterans(workspace, true); });
  $effect(() => { if (!firstParent && uiRecords[0]) firstParent = uiRecords[0].id; if (!secondParent && uiRecords[1]) secondParent = uiRecords[1].id; });
  $effect(() => { if (section === 'optimizer' || section === 'affinity' || section === 'planner') void ensureAffinity(); });
  $effect(() => {
    if (section !== 'planner') return;
    const query = raceSearch;
    const token = ++scheduleToken;
    scheduleLoading = true;
    const timeout = window.setTimeout(() => { void loadRaceSchedule(query).then((years) => { if (token === scheduleToken) scheduleYears = years; }).catch((error) => { if (token === scheduleToken) actionError = error instanceof Error ? error.message : 'Race schedule could not be loaded.'; }).finally(() => { if (token === scheduleToken) scheduleLoading = false; }); }, 160);
    return () => window.clearTimeout(timeout);
  });
  $effect(() => { targetCharacterId; $activeWorkspace.id; pairRankings = []; });
</script>

<svelte:head><title>Veterans · uma.moe</title><meta name="description" content="Manage, import, export, optimize, and compare Uma Musume Veterans in a local-first workspace."/></svelte:head>
<AppPage routeId="veterans" title="Veterans" description="The moe Veteran library and Hakuraku tools share one local-first, versioned workspace." eyebrow="Local-first" width="normal">
  {#snippet actions()}<WorkspaceSwitcher/><Button variant="secondary" icon="download" disabled={!uiRecords.length} onclick={exportAll}>Export</Button><Button icon="add" onclick={() => addOpen = true}>Add Veteran</Button>{/snippet}
  <Tabs items={sections} bind:value={section} label="Veteran tools"/>
  {#if $veteranRecordsError}<Banner title="Veteran storage unavailable" tone="danger"><p>{$veteranRecordsError}</p></Banner>{/if}{#if actionError}<Banner title="Veteran action failed" tone="danger" dismissible><p>{actionError}</p></Banner>{/if}{#if importMessage}<Banner title={importMessage} tone="success" dismissible/>{/if}
  {#if section === 'library'}
    <section class="library-layout"><div class="library-list"><Card padding="sm"><div class="filter-row"><TextField id="veteran-search" label="Search Veterans" type="search" placeholder="Name, card, scenario, factor…" bind:value={search}/><div class="filter-chips"><FilterChip label="Blue factors" selected={factorFilters.includes('stats')} onclick={() => toggleFactor('stats')}/><FilterChip label="Aptitude" selected={factorFilters.includes('aptitude')} onclick={() => toggleFactor('aptitude')}/><FilterChip label="Unique" selected={factorFilters.includes('unique')} onclick={() => toggleFactor('unique')}/><FilterChip label="Skills / races" selected={factorFilters.includes('skills-races')} onclick={() => toggleFactor('skills-races')}/></div></div></Card><ResultToolbar count={filtered.length} noun="Veterans" filtered={Boolean(search) || factorFilters.length > 0} sortOptions={[{ value: 'updated', label: 'Recently updated' }, { value: 'affinity', label: 'Affinity' }, { value: 'score', label: 'Rank score' }]} bind:sort bind:view onrefresh={() => loadVeterans($activeWorkspace.id, true)}/>
      {#if $veteranRecordsLoading}<div class="loading"><Spinner size={28}/><span>Opening {$activeWorkspace.label}…</span></div>{:else if !filtered.length}<EmptyState icon="veterans" title={search || factorFilters.length ? 'No matching Veterans' : 'No Veterans in this workspace'} description={search || factorFilters.length ? 'Try fewer factor categories or a different search.' : 'Import compatible JSON or add a Veteran manually. Nothing is uploaded from the Local workspace.'}/>{:else}<div class="veteran-results" class:grid={view === 'grid'}>{#each filtered as veteran (veteran.id)}<VeteranListItem {veteran} selected={selected?.id === veteran.id} onclick={() => selectedId = veteran.id}>{#snippet actions()}<IconButton icon="download" label={`Export ${veteran.name}`} size="sm" onclick={() => exportOne(veteran.id)}/><IconButton icon="trash" label={`Delete ${veteran.name}`} size="sm" disabled={deleting === veteran.id} onclick={() => remove(veteran.id)}/>{/snippet}</VeteranListItem>{/each}</div>{/if}</div>
      <aside class="veteran-detail">{#if selected}<VeteranSummary veteran={selected}/>{/if}<FileDrop id="veteran-json-import" label="Import Veteran JSON" accept=".json,application/json" multiple onfiles={files}/><small>Imports validate every record before one IndexedDB transaction. Duplicates use trainedCharaId or a deterministic content fingerprint.</small></aside></section>
  {:else if section === 'optimizer'}
    <section class="tool-panel"><header><span>Hakuraku workflow · moe storage</span><h2>Parent pair optimizer</h2><p>Rank every unique pairing from the active workspace using the same row-major aff2/aff3 relation formula as the Angular planner.</p></header>{#if affinityError}<Banner title="Affinity data unavailable" tone="danger"><p>{affinityError}</p></Banner>{/if}{#if !uiRecords.length}<EmptyState icon="veterans" title="Import Veterans first" description="The optimizer never uses sample production data."/>{:else}<div class="optimizer-fields"><SelectField id="optimizer-target" label="Target character" options={targetOptions} bind:value={targetCharacterId}/><VeteranSelector id="optimizer-parent-one" label="Parent 1" options={selectorOptions} bind:value={firstParent}/><VeteranSelector id="optimizer-parent-two" label="Parent 2" options={selectorOptions} bind:value={secondParent}/></div>{#if affinityLoading}<div class="loading"><Spinner size={24}/><span>Loading affinity matrix…</span></div>{:else if relation}<div class="affinity-summary"><div><span>Relation affinity</span><strong>{relation.total}</strong></div><dl><div><dt>P1 branch</dt><dd>{relation.parentOneTotal}</dd></div><div><dt>P2 branch</dt><dd>{relation.parentTwoTotal}</dd></div><div><dt>Parent pair</dt><dd>{relation.parentPair}</dd></div><div><dt>Shared factors</dt><dd>{sharedFactors}</dd></div></dl></div><div class="rank-actions"><p>Ranking is calculated only when requested so large local libraries do not add work during typing or navigation.</p><Button icon="sort" loading={ranking} disabled={uiRecords.length < 2} onclick={rankPairs}>Rank all pairings</Button></div>{#if pairRankings.length}<DataTable caption="Best parent pairings" columns={rankingColumns} rows={rankingRows}/>{/if}{/if}{/if}</section>
  {:else if section === 'affinity'}
    <section class="tool-panel"><header><span>Shared affinity engine</span><h2>Compare lineage inputs</h2><p>Relation affinity is decoded from moe’s demand-loaded aff2/aff3 matrix. Shared factors remain a separate compatibility signal.</p></header>{#if affinityError}<Banner title="Affinity data unavailable" tone="danger"><p>{affinityError}</p></Banner>{/if}{#if uiRecords.length}<div class="optimizer-fields"><SelectField id="affinity-target" label="Target character" options={targetOptions} bind:value={targetCharacterId}/><VeteranSelector id="affinity-parent-one" label="Parent 1" options={selectorOptions} bind:value={firstParent}/><VeteranSelector id="affinity-parent-two" label="Parent 2" options={selectorOptions} bind:value={secondParent}/></div>{#if affinityLoading}<div class="loading"><Spinner size={24}/><span>Loading affinity matrix…</span></div>{:else if relation}<div class="affinity-summary"><div><span>Total relation affinity</span><strong>{relation.total}</strong></div><dl><div><dt>Target ↔ P1</dt><dd>{relation.targetParentOne}</dd></div><div><dt>P1 grandparents</dt><dd>{relation.targetParentOneGrandparentOne + relation.targetParentOneGrandparentTwo}</dd></div><div><dt>Target ↔ P2</dt><dd>{relation.targetParentTwo}</dd></div><div><dt>P2 grandparents</dt><dd>{relation.targetParentTwoGrandparentOne + relation.targetParentTwoGrandparentTwo}</dd></div><div><dt>P1 ↔ P2</dt><dd>{relation.parentPair}</dd></div><div><dt>Shared factors</dt><dd>{sharedFactors}</dd></div></dl></div><div class="affinity-actions"><Button variant="secondary" icon="star" onclick={() => sparkOpen = true}>Spark odds</Button><Button variant="secondary" icon="calendar" onclick={() => section = 'planner'}>Plan races</Button></div><small class="formula-note">Race affinity is kept separate until a Veteran supplies verifiable G1 saddle data; this number is never inflated with guessed race values.</small>{/if}{:else}<EmptyState icon="lineage" title="No lineage inputs" description="Add or import Veterans to compare them."/>{/if}</section>
  {:else}
    <section class="tool-panel planner-panel"><header><span>Canonical moe schedule</span><h2>Race planner</h2><p>The Hakuraku planner is replaced by the existing uma.moe calendar contract, backed by the complete race-to-saddle dataset and the same selected lineage inputs.</p></header>
      {#if uiRecords.length}<div class="optimizer-fields"><SelectField id="planner-target" label="Target character" options={targetOptions} bind:value={targetCharacterId}/><VeteranSelector id="planner-parent-one" label="Parent 1" options={selectorOptions} bind:value={firstParent}/><VeteranSelector id="planner-parent-two" label="Parent 2" options={selectorOptions} bind:value={secondParent}/></div>{/if}
      <div class="planner-toolbar"><TextField id="planner-race-search" label="Search races" type="search" placeholder="Race name or grade…" bind:value={raceSearch}/><div><span>{selectedRaceIds.length} planned race{selectedRaceIds.length === 1 ? '' : 's'}</span>{#if selectedRaceIds.length}<Button variant="ghost" size="sm" onclick={() => selectedRaceIds = []}>Clear plan</Button>{/if}{#if relation}<Button variant="secondary" size="sm" icon="star" onclick={() => sparkOpen = true}>Spark odds</Button>{/if}</div></div>
      {#if scheduleLoading}<div class="loading"><Spinner size={24}/><span>Opening race schedule…</span></div>{:else}<RaceSchedule years={plannedYears} onselect={(race) => toggleRace(race.id)}/>{/if}
    </section>
  {/if}
</AppPage>

<SparkProcDialog bind:open={sparkOpen} parentOne={parentOne} parentTwo={parentTwo} {relation}/>
<Dialog id="add-veteran" bind:open={addOpen} title="Add Veteran" description="Create a normalized record in the active workspace." mobileSheet>
  <form class="add-form" onsubmit={(event) => { event.preventDefault(); void addVeteran(); }}><TextField id="new-veteran-name" label="Display name" placeholder="Optional" bind:value={newName}/><TextField id="new-veteran-card" label="Character card ID" type="number" min={1} bind:value={newCardId}/><TextField id="new-veteran-rank" label="Rank score" type="number" min={0} bind:value={newRankScore}/><div class="stat-form"><TextField id="new-speed" label="Speed" type="number" min={0} bind:value={newSpeed}/><TextField id="new-stamina" label="Stamina" type="number" min={0} bind:value={newStamina}/><TextField id="new-power" label="Power" type="number" min={0} bind:value={newPower}/><TextField id="new-guts" label="Guts" type="number" min={0} bind:value={newGuts}/><TextField id="new-wisdom" label="Wit" type="number" min={0} bind:value={newWisdom}/></div><div class="dialog-actions"><Button variant="secondary" onclick={() => addOpen = false}>Cancel</Button><Button type="submit" loading={saving} disabled={!Number(newCardId)}>Save Veteran</Button></div></form>
</Dialog>

<style>
  .library-layout { min-width:0; display:grid; grid-template-columns:minmax(0,1.25fr) minmax(340px,.75fr); align-items:start; gap:var(--space-4); }.library-list,.veteran-detail,.veteran-results { min-width:0; display:grid; gap:var(--space-3); }.veteran-detail { position:sticky; top:calc(var(--utility-height) + var(--space-3)); }.veteran-detail > small { color:var(--color-text-subtle); font-size:9px; line-height:1.5; }.filter-row { display:grid; grid-template-columns:minmax(220px,.7fr) minmax(0,1fr); align-items:end; gap:var(--space-3); }.filter-chips { min-width:0; display:flex; flex-wrap:wrap; gap:4px; }.veteran-results.grid { grid-template-columns:repeat(auto-fill,minmax(310px,1fr)); }.loading { min-height:180px; display:flex; align-items:center; justify-content:center; gap:var(--space-3); color:var(--color-text-muted); }
  .tool-panel { min-width:0; display:grid; gap:var(--space-4); padding:var(--space-4); border:1px solid var(--border-primary); border-radius:var(--radius-lg); background:var(--surface-1); }.tool-panel header > span { color:var(--color-accent); font-size:9px; font-weight:800; text-transform:uppercase; }.tool-panel h2 { margin:2px 0; font-size:var(--font-lg); }.tool-panel p { margin:0; font-size:var(--font-xs); }.optimizer-fields { display:grid; grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr)); align-items:end; gap:var(--space-3); }
  .affinity-summary { display:grid; grid-template-columns:minmax(150px,.3fr) minmax(0,1fr); align-items:stretch; border:1px solid var(--border-primary); border-radius:var(--radius-md); overflow:hidden; background:var(--surface-2); }.affinity-summary > div { display:grid; align-content:center; justify-items:center; padding:var(--space-3); border-right:1px solid var(--border-subtle); }.affinity-summary > div span { color:var(--color-text-muted); font-size:9px; font-weight:800; text-transform:uppercase; }.affinity-summary > div strong { color:var(--accent-secondary); font:800 2rem/1 var(--font-mono); }.affinity-summary dl { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); margin:0; }.affinity-summary dl div { display:grid; align-content:center; justify-items:center; min-height:56px; padding:6px; border-left:1px solid var(--border-subtle); }.affinity-summary dt { color:var(--color-text-subtle); font-size:8px; font-weight:800; text-transform:uppercase; }.affinity-summary dd { margin:2px 0 0; font:750 var(--font-md)/1 var(--font-mono); }.rank-actions { display:flex; align-items:center; justify-content:space-between; gap:var(--space-4); }.rank-actions p { max-width:660px; color:var(--color-text-muted); }.formula-note { color:var(--color-text-subtle); font-size:9px; }
  .affinity-actions { display:flex; flex-wrap:wrap; gap:6px; }.planner-toolbar { display:grid; grid-template-columns:minmax(220px,.55fr) minmax(0,1fr); align-items:end; gap:var(--space-3); }.planner-toolbar > div { min-height:var(--control-height); display:flex; align-items:center; justify-content:flex-end; flex-wrap:wrap; gap:6px; }.planner-toolbar span { margin-right:auto; color:var(--color-text-muted); font-size:10px; }.planner-panel { overflow:hidden; }
  .add-form { display:grid; gap:var(--space-3); }.stat-form { display:grid; grid-template-columns:repeat(5,minmax(0,1fr)); gap:5px; }.dialog-actions { display:flex; justify-content:flex-end; gap:var(--space-2); padding-top:var(--space-3); border-top:1px solid var(--border-subtle); }
  @media (max-width:900px) { .library-layout { grid-template-columns:1fr; }.veteran-detail { position:static; }.affinity-summary dl { grid-template-columns:repeat(2,minmax(0,1fr)); } }@media (max-width:580px) { .filter-row,.planner-toolbar { grid-template-columns:1fr; }.tool-panel { padding-inline:4px; }.stat-form { grid-template-columns:repeat(2,minmax(0,1fr)); }.dialog-actions > :global(button) { flex:1; }.affinity-summary { grid-template-columns:1fr; }.affinity-summary > div { border-right:0; border-bottom:1px solid var(--border-subtle); }.affinity-summary dl { grid-template-columns:repeat(2,minmax(0,1fr)); }.rank-actions { align-items:stretch; flex-direction:column; }.rank-actions :global(button) { width:100%; }.planner-toolbar > div { justify-content:flex-start; }.planner-toolbar span { width:100%; } }
</style>
