import { UqlCompiler } from './uql-compiler';
import { maskUqlStrings, uqlDelimiterIssue } from './uql-text';
import { splitUqlClauses } from './uql-context';
import type { InheritanceSort } from './inheritance-search';


export type UqlValidationState = 'empty' | 'incomplete' | 'invalid' | 'valid';
export interface UqlValidation { state: UqlValidationState; message: string; compiled: string; sortBy?: InheritanceSort; explicitFollowerFilter: boolean; }

const fields = new Set([
  'inheritance_id', 'follower_num', 'followers', 'main_parent_id', 'parent_left_id', 'left_parent_id', 'parent_right_id', 'right_parent_id',
  'main_chara_id', 'left_chara_id', 'right_chara_id', 'parent_rank', 'parent_rarity', 'win_count', 'wins', 'white_count',
  'common_white_count', 'common_white_stars_sum', 'scenario_white_count', 'scenario_white_stars_sum', 'race_white_count', 'race_white_stars_sum',
  'main_common_white_count', 'main_common_white_stars_sum', 'main_scenario_white_count', 'main_scenario_white_stars_sum', 'main_race_white_count',
  'main_race_white_stars_sum', 'main_blue_factors', 'main_pink_factors', 'main_green_factors', 'main_white_count', 'left_blue_factors',
  'left_pink_factors', 'left_green_factors', 'left_white_count', 'right_blue_factors', 'right_pink_factors', 'right_green_factors', 'right_white_count',
  'blue_stars_sum', 'pink_stars_sum', 'red_stars_sum', 'green_stars_sum', 'white_stars_sum', 'scenario_id', 'scenario', 'affinity', 'affinity_score',
  'race_affinity', 'computed_race_affinity', 'support_card_count', 'support_cards_count', 'support_card_id', 'limit_break_count', 'account_id',
  'trainer_id', 'trainer_name', 'name', 'blue_sparks', 'pink_sparks', 'green_sparks', 'white_sparks', 'main_white_factors', 'main_white_sparks',
  'left_white_factors', 'left_white_sparks', 'right_white_factors', 'right_white_sparks', 'main_win_saddles', 'left_win_saddles', 'right_win_saddles', 'race_results'
]);
const functions = new Set(['contains', 'has', 'overlaps', 'any', 'has_all', 'contains_all', 'all', 'support_card', 'has_support_card', 'spark_sum', 'optional_white', 'optional_main_white', 'optional_any_white', 'lineage_white']);
const keywords = new Set(['where', 'and', 'or', 'not', 'in', 'between', 'like', 'ilike', 'mod', 'true', 'false', 'null']);
const functionParameters = new Set([
  'id', 'card_id', 'support_card_id', 'lb', 'limitbreak', 'limit_break', 'limit_break_count', 'exp', 'experience',
  'priority', 'priority_group', 'prio_group', 'group', 'type_weight', 'level_weight', 'match_weight', 'stack_weight',
  'occurrence_weight', 'base', 'decay', 'weight', 'proc_weight', 'proc_kind'
]);
const sortAliases: Record<string, InheritanceSort> = {
  trending: 'trending', affinity: 'affinity_score', 'total affinity': 'affinity_score', affinity_score: 'affinity_score',
  wins: 'win_count', 'g1 wins': 'win_count', win_count: 'win_count', whites: 'white_count', 'white count': 'white_count', white_count: 'white_count',
  score: 'parent_rank', rank: 'parent_rank', parent_rank: 'parent_rank', newest: 'last_updated', 'newest first': 'last_updated', last_updated: 'last_updated',
  followers: 'follower_num', follower_num: 'follower_num', blue_stars_sum: 'blue_stars_sum', 'total blue stars': 'blue_stars_sum',
  pink_stars_sum: 'pink_stars_sum', 'total pink stars': 'pink_stars_sum', 'total red stars': 'pink_stars_sum',
  green_stars_sum: 'green_stars_sum', 'total green stars': 'green_stars_sum', white_stars_sum: 'white_stars_sum',
  'total white stars': 'white_stars_sum', 'white skills amount': 'white_count'
};

const withoutStrings = maskUqlStrings;

// Backend value lists accept literals only, including lists generated by friendly operators.
function hasNestedInList(query: string): boolean {
  const text = maskUqlStrings(query);
  const pattern = /\b(?:not\s+)?in\s*\(|\b(?:overlaps|has_all|contains_all|all)\s*\(\s*[^,()]+\s*,\s*\(/gi;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(text))) {
    const start = pattern.lastIndex - 1;
    let depth = 0;
    for (let index = start; index < text.length; index++) {
      if (text[index] === '(' && ++depth > 1) return true;
      if (text[index] === ')' && --depth === 0) { pattern.lastIndex = index + 1; break; }
    }
  }
  return false;
}

export function validateInheritanceUql(value: string, compiler?: UqlCompiler): UqlValidation {
  const normalized = value.trim().replace(/;\s*$/, '').trim();
  if (!normalized) return { state: 'empty', message: '', compiled: '', explicitFollowerFilter: false };
  const delimiters = uqlDelimiterIssue(normalized); if (delimiters) return { ...delimiters, compiled: '', explicitFollowerFilter: false };
  const editable = normalized.replace(/^where\b\s*/i, '').trim();
  if (!editable || /(?:\bwhere\b|\band\b|\bor\b|\bnot\b|\bin\b|\bbetween\b|\blike\b|\bilike\b|\bmod\b|\bhas\b|\bhas\s+any\b|\bhas\s+all\b|\bdoes\s+not\s+have\b|\bcontains\b|\bcontains\s+any\b|\bcontains\s+all\b|[,(+\-*\/%]|=|!=|<>|<=|>=|<|>)$/i.test(editable)) return { state: 'incomplete', message: 'Finish the predicate', compiled: '', explicitFollowerFilter: false };
  if (/\b(?:in|has|has_all|contains_all|overlaps)\s*\[\s*\]/i.test(withoutStrings(editable))) return { state: 'incomplete', message: 'Choose at least one value', compiled: '', explicitFollowerFilter: false };
  if (/(?:^|[\s(])(?:has\s+any|has\s+all|contains\s+any|contains\s+all|not\s+in|in)\s*\(\s*\)(?=\s*(?:\)|;|$|\band\b|\bor\b))/i.test(withoutStrings(editable)) || /\b(?:overlaps|has_all|contains_all|all)\s*\(\s*[^,()]+\s*,\s*\(\s*\)\s*\)/i.test(withoutStrings(editable))) return { state: 'incomplete', message: 'Choose at least one skill', compiled: '', explicitFollowerFilter: false };
  const continuation = editable.match(/(?:\d|'|"|\))\s+([A-Za-z]+)$/)?.[1]?.toLowerCase();
  if (continuation && ['a', 'an', 'o'].includes(continuation)) return { state: 'incomplete', message: 'Finish the boolean operator', compiled: '', explicitFollowerFilter: false };

  let sortBy: InheritanceSort | undefined; const predicates: string[] = [];
  for (const clause of splitUqlClauses(editable)) {
    const directive = clause.match(/^sort(?:\s+by)?\s*(?:=|==|is)?\s*\[?\s*([^\]]+?)\s*\]?$/i);
    if (directive) {
      const requested = directive[1]?.replace(/^['"]|['"]$/g, '').trim().toLocaleLowerCase() ?? '';
      sortBy = sortAliases[requested]; if (!sortBy) return { state: 'invalid', message: `Unknown sort: ${requested}`, compiled: '', explicitFollowerFilter: false };
    } else predicates.push(clause);
  }
  const compiled = (compiler ?? new UqlCompiler()).compile(predicates.join(' and '));
  const identifierText = withoutStrings(compiled);
  if (hasNestedInList(compiled)) return { state: 'invalid', message: 'IN lists only accept literal values, not nested functions', compiled: '', sortBy, explicitFollowerFilter: false };
  for (const match of identifierText.matchAll(/[A-Za-z_][A-Za-z0-9_.]*/g)) {
    const identifier = match[0].toLowerCase().replace(/\./g, '_');
    if (fields.has(identifier) || keywords.has(identifier) || functions.has(identifier) || functionParameters.has(identifier)) continue;
    const functionCall = identifierText.slice(match.index + match[0].length).trimStart().startsWith('(');
    return { state: 'invalid', message: `Unknown field or function: ${match[0]}${functionCall ? '()' : ''}`, compiled: '', sortBy, explicitFollowerFilter: false };
  }
  if (!compiled && !sortBy) return { state: 'incomplete', message: 'Finish the predicate', compiled: '', explicitFollowerFilter: false };
  return { state: 'valid', message: 'Ready', compiled, sortBy, explicitFollowerFilter: /\b(?:follower_num|followers)\b/i.test(identifierText) };
}
