<script lang="ts">
  import Icon from './Icon.svelte';
  export interface FilterPreset { id: string; name: string; activeCount: number; mode?: string; }
  interface Props { presets: FilterPreset[]; draft?: string; message?: string; onsave?: (name: string) => void; onload?: (preset: FilterPreset) => void; ondelete?: (preset: FilterPreset) => void; onexport?: () => void; onimport?: () => void; }
  let { presets, draft = $bindable(''), message, onsave, onload, ondelete, onexport, onimport }: Props = $props();
  function save() { const name = draft.trim(); if (name) onsave?.(name); }
</script>

<details class="presets">
  <summary><Icon name="star" size={15}/><span>Presets</span>{#if presets.length}<small>{presets.length}</small>{/if}</summary>
  <div class="panel">
    <header><strong>Filter presets</strong><small>{presets.length}</small><span class="utilities">{#if onexport}<button type="button" aria-label="Export presets" disabled={!presets.length} onclick={onexport}><Icon name="download" size={14}/></button>{/if}{#if onimport}<button type="button" aria-label="Import presets" onclick={onimport}><Icon name="upload" size={14}/></button>{/if}</span></header>
    <div class="save-row"><label><span class="sr-only">Preset name</span><input bind:value={draft} maxlength="60" placeholder="Preset name" onkeydown={(event) => { if (event.key === 'Enter') save(); }}/></label><button type="button" aria-label="Save current filters" disabled={!draft.trim()} onclick={save}><Icon name="add" size={16}/></button></div>
    {#if message}<p>{message}</p>{/if}
    <div class="list">
      {#each presets as preset (preset.id)}
        <div><button type="button" class="load" onclick={() => onload?.(preset)}><span>{preset.name}</span><span class="meta"><small>{preset.activeCount} filter{preset.activeCount === 1 ? '' : 's'}</small>{#if preset.mode}<i>{preset.mode}</i>{/if}</span></button>{#if ondelete}<button type="button" class="delete" aria-label={`Delete ${preset.name}`} onclick={() => ondelete(preset)}><Icon name="trash" size={14}/></button>{/if}</div>
      {:else}<span class="empty"><Icon name="star" size={15}/>No presets yet</span>{/each}
    </div>
  </div>
</details>

<style>
  .presets { position: relative; }
  summary { width:auto;height:34px;box-sizing:border-box;display:flex;align-items:center;justify-content:center;gap:5px;padding:0 8px;border:1px solid var(--filter-mode-toggle-border);border-radius:var(--radius-sm);background:var(--filter-mode-toggle-bg);color:var(--factor-field-text);cursor:pointer;list-style:none;font-size:12px;font-weight:800;line-height:1;transition:background var(--duration-fast),border-color var(--duration-fast),color var(--duration-fast); } summary::-webkit-details-marker { display: none; } summary:hover,.presets[open] summary{border-color:rgb(var(--accent-primary-rgb)/.4);background:var(--filter-mode-active-bg);color:var(--filter-mode-active-color)}summary small { min-width:20px;padding:2px 5px;border:1px solid rgb(var(--accent-primary-rgb)/.3);border-radius:var(--radius-pill);background:rgb(var(--accent-primary-rgb)/.16);color:var(--accent-primary);font-size:9px;line-height:1.2;text-align:center; }
  .panel { position:absolute;z-index:var(--z-overlay);top:calc(100% + 8px);right:0;width:min(348px,calc(100vw - 24px));padding:8px;border:1px solid var(--border-secondary);border-radius:var(--radius-md);background:var(--factor-panel-bg);box-shadow:var(--shadow-dropdown),0 0 0 1px rgb(0 0 0/.3); }
  header { min-height:28px;display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:center;gap:7px;padding:0 2px 8px;border-bottom:1px solid var(--border-subtle);color:var(--text-secondary);font-size:10px;font-weight:800;letter-spacing:.05em;text-transform:uppercase; } header small { min-width:18px;height:18px;padding:0 5px;border-radius:9px;background:rgb(var(--accent-primary-rgb)/.14);color:var(--accent-primary);font-size:9px;line-height:18px;text-align:center }.utilities{display:flex;gap:4px}.utilities button{width:24px;height:24px;display:grid;place-items:center;padding:0;border:1px solid var(--border-subtle);border-radius:var(--radius-xs);background:var(--factor-field-bg);color:var(--text-secondary);cursor:pointer}.utilities button:hover:not(:disabled){border-color:rgb(var(--accent-primary-rgb)/.32);background:rgb(var(--accent-primary-rgb)/.12);color:var(--accent-primary)}.utilities button:disabled{opacity:.35}
  .save-row { display:grid;grid-template-columns:minmax(0,1fr) 34px;align-items:center;gap:8px;padding:8px 0 0; } label { min-width:0; } input { width:100%;height:34px;box-sizing:border-box;padding:0 10px;border:1px solid var(--border-primary);border-radius:var(--radius-sm);outline:0;background:var(--factor-field-bg);color:var(--text-primary);font:inherit;font-size:12px; }input:focus{border-color:var(--db-control-focus-border);box-shadow:0 0 0 3px rgb(var(--accent-primary-rgb)/.08)} .save-row button { width:34px;height:34px;display:grid;place-items:center;padding:0;border:1px solid rgb(var(--accent-primary-rgb)/.3);border-radius:var(--radius-sm);background:rgb(var(--accent-primary-rgb)/.16);color:var(--accent-primary);cursor:pointer; } .save-row button:disabled { border-color:var(--border-subtle);background:var(--factor-field-bg);color:var(--text-disabled);cursor:default; }
  p { min-height:16px;margin:0;padding:6px 3px 0;color:var(--accent-primary);font-size:10px;font-weight:600; }
  .list { max-height:240px;display:grid;gap:4px;margin-top:7px;overflow-y:auto; } .list > div { display:grid;grid-template-columns:minmax(0,1fr) 34px;align-items:center;gap:8px; } .load { min-width:0;height:36px;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:7px;padding:0 7px 0 10px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--factor-field-bg);color:var(--text-primary);cursor:pointer;text-align:left; } .load:hover { border-color:rgb(var(--accent-primary-rgb)/.34);background:rgb(var(--accent-primary-rgb)/.1);color:var(--filter-mode-active-color); } .load>span:first-child { min-width:0;overflow:hidden;font-size:11px;font-weight:700;text-overflow:ellipsis;white-space:nowrap; }.meta{display:flex;align-items:center;gap:4px}.load small,.load i{height:20px;padding:0 5px;border:1px solid rgb(var(--on-surface-rgb)/.08);border-radius:var(--radius-xs);background:rgb(var(--on-surface-rgb)/.05);color:var(--text-secondary);font-size:8px;font-style:normal;font-weight:800;line-height:18px;white-space:nowrap}.load i{border-color:rgb(var(--accent-primary-rgb)/.2);background:rgb(var(--accent-primary-rgb)/.1);color:var(--accent-primary);text-transform:uppercase}.delete { width:34px;height:34px;display:grid;place-items:center;padding:0;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--factor-field-bg);color:var(--text-muted);cursor:pointer; } .delete:hover { border-color:rgb(var(--accent-error-rgb)/.3);background:rgb(var(--accent-error-rgb)/.12);color:var(--accent-error); } .empty { min-height:40px;display:flex;align-items:center;justify-content:center;gap:6px;padding:0 12px;border:1px dashed var(--border-primary);border-radius:var(--radius-sm);background:var(--factor-field-bg);color:var(--text-secondary);font-size:10px;font-weight:600;text-align:center; }
  @media(max-width:600px){summary{height:36px}.panel{right:-4px;width:calc(100vw - 28px);max-width:calc(100vw - 28px)}}
  @media(pointer: coarse) and (max-width: 1300px){summary{height:50px}.utilities button,.save-row button,.delete{width:var(--touch-target);height:var(--touch-target)}.save-row,.list>div{grid-template-columns:minmax(0,1fr) 44px}input,.load{height:var(--touch-target)}}
</style>
